---
- name: install prerequisites
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - dkms
    - unzip

- name: install virtualbox apt key
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: install repository
  apt_repository: 
    repo: deb http://download.virtualbox.org/virtualbox/debian {{ distribution }} contrib
    state: present
    update_cache: yes

- name: install required software
  apt: pkg=virtualbox-5.1 state=present

 - name: check if extension pack is already installed
   shell: VBoxManage list extpacks
   register: extpack_list
   changed_when: 'extpack_list.stdout == "Extension Packs: 0"'

 - name: detect version
   shell: |
     version=$(VBoxManage -v)
     var1=$(echo $version | cut -d 'r' -f 1)
     var2=$(echo $version | cut -d 'r' -f 2)
     echo $var1
     echo $var2
   register: virtualbox_version
   when: 'extpack_list.stdout == "Extension Packs: 0"'

 - debug:  var=virtualbox_version.stdout_lines
   when: 'extpack_list.stdout == "Extension Packs: 0"'

 - name: download VirtualBox extension pack
   get_url:
     url: http://download.virtualbox.org/virtualbox/{{ virtualbox_version.stdout_lines.0 }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout_lines.0 }}-{{ virtualbox_version.stdout_lines.1 }}.vbox-extpack
     dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout_lines.0 }}-{{ virtualbox_version.stdout_lines.1 }}.vbox-extpack
   when: 'extpack_list.stdout == "Extension Packs: 0"'

 - name: Install VirtualBox extension pack
   shell: VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout_lines.0 }}-{{ virtualbox_version.stdout_lines.1 }}.vbox-extpack
   when: 'extpack_list.stdout == "Extension Packs: 0"'

 - name: cleanup
   file:
     path: /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout_lines.0 }}-{{ virtualbox_version.stdout_lines.1 }}.vbox-extpack
     state: absent